🙈 chore: formatting correction and read-only var
Signed-off-by: Adrien Kara <adrien@iglou.eu>

diff --git a/build-certs b/build-certs
--- a/build-certs
+++ b/build-certs
@@ -1,8 +1,8 @@
 #!/bin/bash
 set -xe
 
-RED='\e[1;31m'
-GREEN='\e[1;32m'
+declare -r RED='\e[1;31m'
+declare -r GREEN='\e[1;32m'
 
 declare -x CALL_TO
 
@@ -34,7 +34,7 @@ ROOTCA=OK
 intermediate() {
 INTERMEDIATECA=OK
 if [ ! -e cacerts/rootca.crt ] && [ ! -e cacerts/rootca.key ]; then
-        echo -e $RED "You must first create a certificate for the root authority."
+        echo -e "$RED" "You must first create a certificate for the root authority."
         exit 1
 fi
 
@@ -45,7 +45,7 @@ server() {
 SERVERCERT=OK
 [ -x ./scripts/clean-values ] && ./scripts/clean-values;tput init
 if [ ! -e cacerts/intca.crt ] && [ ! -e cacerts/intca.key ]; then
-        echo -e $RED "You must first create a certificate for the root authority and the intermediate autority."
+        echo -e "$RED" "You must first create a certificate for the root authority and the intermediate autority."
         exit 1
 fi
 
@@ -57,72 +57,72 @@ eval set -- "$ARGS"
 while true
 do
         case "$1" in
-                -h|--help) help; ;;
-                -c|--clean-confs) CALL_TO='clean-confs'; shift; ;;
+		-h|--help) help; ;;
+		-c|--clean-confs) CALL_TO='clean-confs'; shift; ;;
 		-b|--clean-database) CALL_TO='clean-database'; shift; ;;
 		-f|--clean-files) CALL_TO='clean-files'; shift; ;;
 		-r|--root) CALL_TO='root'; shift; ;;
-                -i|--intermediate) CALL_TO='intermediate'; shift; ;;
+		-i|--intermediate) CALL_TO='intermediate'; shift; ;;
 		-s|--server) CALL_TO='server'; shift; ;;
-                -n|--country) COUNTRY=$2; shift 2; ;;
-                -p|--province) PROVINCE=$2; shift 2; ;;
+		-n|--country) COUNTRY=$2; shift 2; ;;
+		-p|--province) PROVINCE=$2; shift 2; ;;
 		-l|--locality) LOCALITY=$2; shift 2; ;;
 		-o|--organization) ORGANIZATION=$2; shift 2; ;;
 		-u|--unit) UNIT=$2; shift 2; ;;
 		-m|--domain) DOMAIN=$2; shift 2; ;;
 		-d|--days) DAYS=$2; shift 2; ;;
-                --) shift; break; ;;
-                 *) echo -e $RED "Internal error, unhandled option: $1"; exit 1; ;;
+		--) shift; break; ;;
+		*) echo -e "$RED" "Internal error, unhandled option: $1"; exit 1; ;;
         esac
 done
 
 if [ -z "$COUNTRY" ]; then
-	echo -e $RED "Define a value for the country name."
+	echo -e "$RED" "Define a value for the country name."
 	exit 1
 fi
 
 if [[ "$COUNTRY" != [A-Z][A-Z] ]]; then
-	echo -e $RED "The name of the country may not contain any characters other than two capital letters."
+	echo -e "$RED" "The name of the country may not contain any characters other than two capital letters."
 	exit 1
 fi
 
 if [ -z "$PROVINCE" ]; then
-	echo -e $RED "Define a value for the state or the province name."
+	echo -e "$RED" "Define a value for the state or the province name."
 	exit 1
 fi
 
 if [ -z "$LOCALITY" ]; then
-	echo -e $RED "Define a value for the name of the locality."
+	echo -e "$RED" "Define a value for the name of the locality."
 	exit 1
 fi
 
 if [ -z "$ORGANIZATION" ]; then
-	echo -e $RED "Define a value for the name of your organization."
+	echo -e "$RED" "Define a value for the name of your organization."
 	exit 1
 fi
 
 if [ -z "$UNIT" ]; then
-	echo -e $RED "Define a value for the name of your organizational unit."
+	echo -e "$RED" "Define a value for the name of your organizational unit."
 	exit 1
 fi
 
 if [ -z "$DOMAIN" ]; then
-	echo -e $RED "Define a value for the common name (FQDN or hostname)."
+	echo -e "$RED" "Define a value for the common name (FQDN or hostname)."
 	exit 1
 fi
 
 if [ -z "$DAYS" ]; then
-	echo -e $RED "Define a value for the duration of your certification autority or your server cert."
+	echo -e "$RED" "Define a value for the duration of your certification autority or your server cert."
 	exit 1
 fi
 
 if [[ "$DAYS" != [0-9][0-9]?? ]]; then
-	echo -e $RED "The number of the certificate validity may not contain any characters other than two, three or four numbers."
+	echo -e "$RED" "The number of the certificate validity may not contain any characters other than two, three or four numbers."
 	exit 1
 fi
 
 if [ -z "$ROOTCA" ] && [ -z "$INTERMEDIATECA" ] && [ -z "$SERVERCERT" ]; then
-	echo -e $RED "You must define whether it's a root, intermediate authority or a server certificate."
+	echo -e "$RED" "You must define whether it's a root, intermediate authority or a server certificate."
 	exit 1
 fi
 
