✨ feat: use global var and make some functions
Signed-off-by: Adrien Kara <adrien@iglou.eu>

diff --git a/scripts/intca b/scripts/intca
--- a/scripts/intca
+++ b/scripts/intca
@@ -1,25 +1,49 @@
 #!/bin/bash
 
-set -e
+intermediate() {
+        local _key="$CAKEY/intca.key"
+        local _csr="$CACSR/intca.csr"
+        local _crt="$CACRT/intca.crt"
 
-sed -i "s/C = .*/C =/g" confs/ca.cnf
-sed -i "s/ST = .*/ST =/g" confs/ca.cnf
-sed -i "s/L = .*/L =/g" confs/ca.cnf
-sed -i "s/O = .*/O =/g" confs/ca.cnf
-sed -i "s/OU = .*/OU =/g" confs/ca.cnf
-sed -i "s/CN = .*/CN =/g" confs/ca.cnf
-sed -i "s/C =/C = $COUNTRY/g" confs/ca.cnf
-sed -i "s/ST =/ST = $PROVINCE/g" confs/ca.cnf
-sed -i "s/L =/L = $LOCALITY/g" confs/ca.cnf
-sed -i "s/O =/O = $ORGANIZATION/g" confs/ca.cnf
-sed -i "s/OU =/OU = $UNIT/g" confs/ca.cnf
-sed -i "s/CN =/CN = $DOMAIN/g" confs/ca.cnf
+        if [ ! -e "$CACRT/rootca.crt" ] && [ ! -e "$CACRT/rootca.key" ]; then
+                echo -e "$RED" "You must first create a certificate for the root authority."
+                exit 1
+        fi
 
-#Generate the private key
-openssl genrsa -out cakey/intca.key 4096
-#Generate the CSR
-openssl req -sha512 -new -subj "/C=$COUNTRY/ST=$PROVINCE/O=$ORGANIZATION/OU=$UNIT/L=$LOCALITY/CN=$DOMAIN" -key cakey/intca.key -out cacsr/intca.csr
-#Generate the intermediate certificate
-openssl ca -batch -config confs/ca.cnf -days $DAYS -extensions v3_ca -subj "/C=$COUNTRY/ST=$PROVINCE/O=$ORGANIZATION/OU=$UNIT/L=$LOCALITY/CN=$DOMAIN" -notext -in cacsr/intca.csr -out cacerts/intca.crt
-#Deletion of all *.pem generated by OpenSSL to keep only the .crt
-rm -f cacerts/*.pem
+        sed -i "s/C = .*/C =/g" "$CFG/ca.cnf"
+        sed -i "s/ST = .*/ST =/g" "$CFG/ca.cnf"
+        sed -i "s/L = .*/L =/g" "$CFG/ca.cnf"
+        sed -i "s/O = .*/O =/g" "$CFG/ca.cnf"
+        sed -i "s/OU = .*/OU =/g" "$CFG/ca.cnf"
+        sed -i "s/CN = .*/CN =/g" "$CFG/ca.cnf"
+        sed -i "s/C =/C = $COUNTRY/g" "$CFG/ca.cnf"
+        sed -i "s/ST =/ST = $PROVINCE/g" "$CFG/ca.cnf"
+        sed -i "s/L =/L = $LOCALITY/g" "$CFG/ca.cnf"
+        sed -i "s/O =/O = $ORGANIZATION/g" "$CFG/ca.cnf"
+        sed -i "s/OU =/OU = $UNIT/g" "$CFG/ca.cnf"
+        sed -i "s/CN =/CN = $DOMAIN/g" "$CFG/ca.cnf"
+
+        #Generate the private key
+        if openssl genrsa -out "$_key" 4096; then
+                success "Private key generated"
+        else
+                fatal "Fail to generate private key"
+        fi
+
+        #Generate the CSR
+        if openssl req -sha512 -new -subj "/C=$COUNTRY/ST=$PROVINCE/O=$ORGANIZATION/OU=$UNIT/L=$LOCALITY/CN=$DOMAIN" -key "$_key" -out "$_csr"; then
+                success "CSR generated"
+        else
+                fatal "Fail to generate the CSR"
+        fi
+
+        #Generate the intermediate certificate
+        if openssl ca -batch -config "$CFG/ca.cnf" -days "$DAYS" -extensions v3_ca -subj "/C=$COUNTRY/ST=$PROVINCE/O=$ORGANIZATION/OU=$UNIT/L=$LOCALITY/CN=$DOMAIN" -notext -in "$_csr" -out "$_crt"; then
+                success "Intermediate certificate generated"
+        else
+                fatal "Fail to generate the ntermediate certificate"
+        fi
+
+        #Deletion of all *.pem generated by OpenSSL to keep only the .crt
+        rm -f "$CACRT/"*.pem
+}
